version: '3.5'

services:
  app:
    build: .
    container_name: app
    volumes:
      - .:/app:delegated
    working_dir: /app
    ports:
      - 9001:9000

  webserver:
    image: nginx:latest
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d/:/etc/nginx/conf.d/
      - .:/app:delegated
    depends_on:
      - app

  database:
    image: mysql:8.0
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
