parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
  CauldronOverflowWeb\:
    resource: '../src/'
  CauldronOverflow\:
    resource: '../../../src/CauldronOverflow/'
  Shared\:
    resource: '../../../src/Shared/'

  CauldronOverflow\Infrastructure\Services\MarkdownHelper:
    arguments:
      $isDebug: '%kernel.debug%'

  CauldronOverflow\Infrastructure\Persistence\Question\MysqlQuestionRepository:
    arguments:
      $entityManager: '@doctrine.orm.entity_manager'

  CauldronOverflow\Infrastructure\Persistence\Answer\MysqlAnswerRepository:
    arguments:
      $entityManager: '@doctrine.orm.entity_manager'

  Shared\Infrastructure\Bus\Query\SymfonyQueryBus:
    arguments:
      $bus: '@query.bus'

  _instanceof:
    Shared\Domain\Bus\Query\QueryHandler:
      tags:
        - { name: messenger.message_handler, bus: query.bus }

    Shared\Domain\Bus\Command\CommandHandler:
      tags:
        - { name: messenger.message_handler, bus: command.bus }

framework:
  messenger:
    default_bus: command.bus
    buses:
      query.bus:
      command.bus:
