parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
  CauldronOverflowWeb\:
    resource: '../src/'
  CauldronOverflow\:
    resource: '../../../src/CauldronOverflow/'
  Shared\:
    resource: '../../../src/Shared/'

  CauldronOverflow\Infrastructure\Services\MarkdownHelper:
    arguments:
      $isDebug: '%kernel.debug%'

  CauldronOverflow\Infrastructure\Persistence\Question\MysqlQuestionRepository:
    arguments:
      $entityManager: '@doctrine.orm.entity_manager'
